Feature/user page
dat256-weedle/weedle pull request #73
Opened 2019-05-07 06:12 UTC by neoncove

2019-05-07 07:14 UTC, ghost submitted a review, later dismissed

2019-05-07 08:06 UTC, ericlp submitted a review, later dismissed

2019-05-07 10:33 UTC, ejohnsson6 submitted a review, later dismissed

2019-05-07 11:18 UTC, ghost approved these changes

2019-05-07 15:22 UTC, Praxzy commented
Telefonen kraschar när jag försöker köra denna branch.

2019-05-07 16:43 UTC, ericlp approved these changes

2019-05-08 07:45 UTC, ejohnsson6 approved these changes

2019-05-08 07:46 UTC, PontusLindblom requested changes
Apparently this doesn't run on my phone since it doesn't include the latest Android fix. Perhaps it would be a good idea to implement the fix in the branch before merging?

2019-05-08 08:47 UTC, PontusLindblom approved these changes

2019-05-08 12:53 UTC, merged